name: Add To Projects
on:
  issues:
    types: [opened]
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add To GitHub projects
        run: >
          gh api graphql -f query='
            mutation ($project_node_id: ID!, $issue_url: String!){
              addProjectV2DraftIssue(input: {projectId: $project_node_id title: $issue_url}) {
                projectItem {
                  id
                }
              }
            }' -f project_node_id=$PROJECT_NODE_ID -f issue_url=$ISSUE_URL
        env:
          PROJECT_NODE_ID: ${secrets.PROJECT_NODE_ID}
          GH_TOKEN: ${secrets.PROJECTS_SECRET}
          ISSUE_URL: ${{ github.event.issue.html_url }}
